[build]
functions = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://gipsy-partners.com/api/sys/analytics.json-pretty?id=1-c89b95bac18d8810ea68d56a32db1aca:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}