[build]
functions = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api*"
  to = "https://gipsy-partners.com/api/sys/analytics.json-pretty:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}