[build]
functions = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://gipsy-partners.com/api/sys/analytics.json-pretty?id=1-c89b95bac18d8810ea68d56a32db1aca&item=comp&user=81&phase=3&from=2023-11-01&to=2023-12-01:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api2/*"
  to = "https://gipsy-partners.com/api/sys/analytics.json-pretty?id=1-c89b95bac18d8810ea68d56a32db1aca&item=comp&user=1&phase=3&from=2023-11-01&to=2023-12-01:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}